export const typesData = [
    { id: 1, type: "bug", color: "#99CC33", img: "/types/bug.png" },
    { id: 2, type: "dark", color: "#333333", img: "/types/dark.png" },
    { id: 3, type: "dragon", color: "#7038F8", img: "/types/dragon.png" },
    { id: 4, type: "electric", color: "#FFCC33", img: "/types/electric.png" },
    { id: 5, type: "fairy", color: "#FF99CC", img: "/types/fairy.png" },
    { id: 6, type: "fight", color: "#FF3333", img: "/types/fight.png" },
    { id: 7, type: "fire", color: "#FF6633", img: "/types/fire.png" },
    { id: 8, type: "flying", color: "#6699FF", img: "/types/flying.png" },
    { id: 9, type: "ghost", color: "#6666CC", img: "/types/ghost.png" },
    { id: 10, type: "grass", color: "#66CC33", img: "/types/grass.png" },
    { id: 11, type: "ground", color: "#FFCC66", img: "/types/ground.png" },
    { id: 12, type: "ice", color: "#22daff", img: "/types/ice.png" },
    { id: 13, type: "normal", color: "#FFCC99", img: "/types/normal.png" },
    { id: 14, type: "poison", color: "#AA66CC", img: "/types/poison.png" },
    { id: 15, type: "psychic", color: "#FF6699", img: "/types/psychic.png" },
    { id: 16, type: "rock", color: "#CC9966", img: "/types/rock.png" },
    { id: 17, type: "steel", color: "#CCCCCC", img: "/types/steel.png" },
    { id: 18, type: "water", color: "#3399FF", img: "/types/water.png" },
  ]